In [ ]:
!pwd

/content

In [ ]:
!pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyspark
  Downloading pyspark-3.3.2.tar.gz (281.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.4/281.4 MB 5.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting py4j==0.10.9.5
  Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 kB 27.8 MB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.3.2-py2.py3-none-any.whl size=281824028 sha256=cfe984d050448b17631cb4293edb2305e7f6bf55049d2d7803371444b12f33b1
  Stored in directory: /root/.cache/pip/wheels/6c/e3/9b/0525ce8a69478916513509d43693511463c6468db0de237c86
Successfully built pyspark
Installing collected packages: py4j, pyspark
  Attempting uninstall: py4j
    Found existing installation: py4j 0.10.9.7
    Uninstalling py4j-0.10.9.7:
      Successfully uninstalled py4j-0.10.9.7
Successfully installed py4j-0.10.9.5 pyspark-3.3.2

In [ ]:
from pyspark.sql import SparkSession

In [ ]:
스파크 = SparkSession.builder.appName('Missing').getOrCreate()  # 세션 만드는데 조금 걸림

In [ ]:
스파크.conf.set("spark.sql.execution.arrow.enabled","true")

In [ ]:
# 스파크DF = 스파크.read.csv("/content/drive/MyDrive/BSA/Employee_missing.csv", header=True, encoding="cp949",inferSchema=True)
스파크DF = 스파크.read.csv("hdfs://localhost:9000/Spark/Employee_missing.csv", header=True, encoding="cp949",inferSchema=True)

In [ ]:
스파크DF.show()  # NaN이 아니라 null

+----+------+----+------+-------+--------+-------+-------+--------+
|  id|gender|educ|jobcat| salary|salbegin|jobtime|prevexp|minority|
+----+------+----+------+-------+--------+-------+-------+--------+
|null|  남성|  12|  null|   null|    null|   null|   null|    null|
|   0|  null|null|사무직|60000.0|    null|     95|   null|     YES|
|null|  null|null|  null|   null|    null|   null|   null|    null|
|   1|  남성|  15|경영자|57000.0|   27000|     98|    144|      No|
|   2|  남성|  16|사무직|40200.0|   18750|     98|     36|      No|
|   3|  여성|  12|사무직|21450.0|   12000|     98|    381|      No|
|   4|  여성|   8|사무직|21900.0|   13200|     98|    190|      No|
|   5|  남성|  15|사무직|45000.0|   21000|     98|    138|      No|
|   6|  남성|  15|사무직|32100.0|   13500|     98|     67|      No|
|   7|  남성|  15|사무직|36000.0|   18750|     98|    114|      No|
|   8|  여성|  12|사무직|21900.0|    9750|     98|      0|      No|
|   9|  여성|  15|사무직|27900.0|   12750|     98|    115|      No|
|  10|  여성|  12|사무직|24000.0|   13500|     98|    244|      No|
|  11|  여성|  16|사무직|30300.0|   16500|     98|    143|      No|
|  12|  남성|   8|사무직|28350.0|   12000|     98|     26|     Yes|
|  13|  남성|  15|사무직|27750.0|   14250|     98|     34|     Yes|
|  14|  여성|  15|사무직|35100.0|   16800|     98|    137|     Yes|
|  15|  남성|  12|사무직|27300.0|   13500|     97|     66|      No|
|  16|  남성|  12|사무직|40800.0|   15000|     97|     24|      No|
|  17|  남성|  15|사무직|46000.0|   14250|     97|     48|      No|
+----+------+----+------+-------+--------+-------+-------+--------+
only showing top 20 rows

삭제

In [ ]:
스파크DF.drop('id').show()  # 컬럼 삭제. 저장하고 싶으면 새 변수에 넣거나 ...

+------+----+------+-------+--------+-------+-------+--------+
|gender|educ|jobcat| salary|salbegin|jobtime|prevexp|minority|
+------+----+------+-------+--------+-------+-------+--------+
|  남성|  12|  null|   null|    null|   null|   null|    null|
|  null|null|사무직|60000.0|    null|     95|   null|     YES|
|  null|null|  null|   null|    null|   null|   null|    null|
|  남성|  15|경영자|57000.0|   27000|     98|    144|      No|
|  남성|  16|사무직|40200.0|   18750|     98|     36|      No|
|  여성|  12|사무직|21450.0|   12000|     98|    381|      No|
|  여성|   8|사무직|21900.0|   13200|     98|    190|      No|
|  남성|  15|사무직|45000.0|   21000|     98|    138|      No|
|  남성|  15|사무직|32100.0|   13500|     98|     67|      No|
|  남성|  15|사무직|36000.0|   18750|     98|    114|      No|
|  여성|  12|사무직|21900.0|    9750|     98|      0|      No|
|  여성|  15|사무직|27900.0|   12750|     98|    115|      No|
|  여성|  12|사무직|24000.0|   13500|     98|    244|      No|
|  여성|  16|사무직|30300.0|   16500|     98|    143|      No|
|  남성|   8|사무직|28350.0|   12000|     98|     26|     Yes|
|  남성|  15|사무직|27750.0|   14250|     98|     34|     Yes|
|  여성|  15|사무직|35100.0|   16800|     98|    137|     Yes|
|  남성|  12|사무직|27300.0|   13500|     97|     66|      No|
|  남성|  12|사무직|40800.0|   15000|     97|     24|      No|
|  남성|  15|사무직|46000.0|   14250|     97|     48|      No|
+------+----+------+-------+--------+-------+-------+--------+
only showing top 20 rows

In [ ]:
# 스파크DF.na.drop().show()
스파크DF.dropna().show()

+---+------+----+------+--------+--------+-------+-------+--------+
| id|gender|educ|jobcat|  salary|salbegin|jobtime|prevexp|minority|
+---+------+----+------+--------+--------+-------+-------+--------+
|  1|  남성|  15|경영자| 57000.0|   27000|     98|    144|      No|
|  2|  남성|  16|사무직| 40200.0|   18750|     98|     36|      No|
|  3|  여성|  12|사무직| 21450.0|   12000|     98|    381|      No|
|  4|  여성|   8|사무직| 21900.0|   13200|     98|    190|      No|
|  5|  남성|  15|사무직| 45000.0|   21000|     98|    138|      No|
|  6|  남성|  15|사무직| 32100.0|   13500|     98|     67|      No|
|  7|  남성|  15|사무직| 36000.0|   18750|     98|    114|      No|
|  8|  여성|  12|사무직| 21900.0|    9750|     98|      0|      No|
|  9|  여성|  15|사무직| 27900.0|   12750|     98|    115|      No|
| 10|  여성|  12|사무직| 24000.0|   13500|     98|    244|      No|
| 11|  여성|  16|사무직| 30300.0|   16500|     98|    143|      No|
| 12|  남성|   8|사무직| 28350.0|   12000|     98|     26|     Yes|
| 13|  남성|  15|사무직| 27750.0|   14250|     98|     34|     Yes|
| 14|  여성|  15|사무직| 35100.0|   16800|     98|    137|     Yes|
| 15|  남성|  12|사무직| 27300.0|   13500|     97|     66|      No|
| 16|  남성|  12|사무직| 40800.0|   15000|     97|     24|      No|
| 17|  남성|  15|사무직| 46000.0|   14250|     97|     48|      No|
| 18|  남성|  16|경영자|103750.0|   27510|     97|     70|      No|
| 19|  남성|  12|사무직| 42300.0|   14250|     97|    103|      No|
| 20|  여성|  12|사무직| 26250.0|   11550|     97|     48|      No|
+---+------+----+------+--------+--------+-------+-------+--------+
only showing top 20 rows

In [ ]:
# 스파크DF.na.drop(how='all').show()
스파크DF.dropna(how='all').show()

+----+------+----+------+--------+--------+-------+-------+--------+
|  id|gender|educ|jobcat|  salary|salbegin|jobtime|prevexp|minority|
+----+------+----+------+--------+--------+-------+-------+--------+
|null|  남성|  12|  null|    null|    null|   null|   null|    null|
|   0|  null|null|사무직| 60000.0|    null|     95|   null|     YES|
|   1|  남성|  15|경영자| 57000.0|   27000|     98|    144|      No|
|   2|  남성|  16|사무직| 40200.0|   18750|     98|     36|      No|
|   3|  여성|  12|사무직| 21450.0|   12000|     98|    381|      No|
|   4|  여성|   8|사무직| 21900.0|   13200|     98|    190|      No|
|   5|  남성|  15|사무직| 45000.0|   21000|     98|    138|      No|
|   6|  남성|  15|사무직| 32100.0|   13500|     98|     67|      No|
|   7|  남성|  15|사무직| 36000.0|   18750|     98|    114|      No|
|   8|  여성|  12|사무직| 21900.0|    9750|     98|      0|      No|
|   9|  여성|  15|사무직| 27900.0|   12750|     98|    115|      No|
|  10|  여성|  12|사무직| 24000.0|   13500|     98|    244|      No|
|  11|  여성|  16|사무직| 30300.0|   16500|     98|    143|      No|
|  12|  남성|   8|사무직| 28350.0|   12000|     98|     26|     Yes|
|  13|  남성|  15|사무직| 27750.0|   14250|     98|     34|     Yes|
|  14|  여성|  15|사무직| 35100.0|   16800|     98|    137|     Yes|
|  15|  남성|  12|사무직| 27300.0|   13500|     97|     66|      No|
|  16|  남성|  12|사무직| 40800.0|   15000|     97|     24|      No|
|  17|  남성|  15|사무직| 46000.0|   14250|     97|     48|      No|
|  18|  남성|  16|경영자|103750.0|   27510|     97|     70|      No|
+----+------+----+------+--------+--------+-------+-------+--------+
only showing top 20 rows

In [ ]:
# 스파크DF.na.drop(thresh=2).show()
스파크DF.dropna(thresh=2).show()

+----+------+----+------+--------+--------+-------+-------+--------+
|  id|gender|educ|jobcat|  salary|salbegin|jobtime|prevexp|minority|
+----+------+----+------+--------+--------+-------+-------+--------+
|null|  남성|  12|  null|    null|    null|   null|   null|    null|
|   0|  null|null|사무직| 60000.0|    null|     95|   null|     YES|
|   1|  남성|  15|경영자| 57000.0|   27000|     98|    144|      No|
|   2|  남성|  16|사무직| 40200.0|   18750|     98|     36|      No|
|   3|  여성|  12|사무직| 21450.0|   12000|     98|    381|      No|
|   4|  여성|   8|사무직| 21900.0|   13200|     98|    190|      No|
|   5|  남성|  15|사무직| 45000.0|   21000|     98|    138|      No|
|   6|  남성|  15|사무직| 32100.0|   13500|     98|     67|      No|
|   7|  남성|  15|사무직| 36000.0|   18750|     98|    114|      No|
|   8|  여성|  12|사무직| 21900.0|    9750|     98|      0|      No|
|   9|  여성|  15|사무직| 27900.0|   12750|     98|    115|      No|
|  10|  여성|  12|사무직| 24000.0|   13500|     98|    244|      No|
|  11|  여성|  16|사무직| 30300.0|   16500|     98|    143|      No|
|  12|  남성|   8|사무직| 28350.0|   12000|     98|     26|     Yes|
|  13|  남성|  15|사무직| 27750.0|   14250|     98|     34|     Yes|
|  14|  여성|  15|사무직| 35100.0|   16800|     98|    137|     Yes|
|  15|  남성|  12|사무직| 27300.0|   13500|     97|     66|      No|
|  16|  남성|  12|사무직| 40800.0|   15000|     97|     24|      No|
|  17|  남성|  15|사무직| 46000.0|   14250|     97|     48|      No|
|  18|  남성|  16|경영자|103750.0|   27510|     97|     70|      No|
+----+------+----+------+--------+--------+-------+-------+--------+
only showing top 20 rows

In [ ]:
# 스파크DF.na.drop(subset=['jobtime']).show()
스파크DF.dropna(subset=['jobtime']).show()

+---+------+----+------+--------+--------+-------+-------+--------+
| id|gender|educ|jobcat|  salary|salbegin|jobtime|prevexp|minority|
+---+------+----+------+--------+--------+-------+-------+--------+
|  0|  null|null|사무직| 60000.0|    null|     95|   null|     YES|
|  1|  남성|  15|경영자| 57000.0|   27000|     98|    144|      No|
|  2|  남성|  16|사무직| 40200.0|   18750|     98|     36|      No|
|  3|  여성|  12|사무직| 21450.0|   12000|     98|    381|      No|
|  4|  여성|   8|사무직| 21900.0|   13200|     98|    190|      No|
|  5|  남성|  15|사무직| 45000.0|   21000|     98|    138|      No|
|  6|  남성|  15|사무직| 32100.0|   13500|     98|     67|      No|
|  7|  남성|  15|사무직| 36000.0|   18750|     98|    114|      No|
|  8|  여성|  12|사무직| 21900.0|    9750|     98|      0|      No|
|  9|  여성|  15|사무직| 27900.0|   12750|     98|    115|      No|
| 10|  여성|  12|사무직| 24000.0|   13500|     98|    244|      No|
| 11|  여성|  16|사무직| 30300.0|   16500|     98|    143|      No|
| 12|  남성|   8|사무직| 28350.0|   12000|     98|     26|     Yes|
| 13|  남성|  15|사무직| 27750.0|   14250|     98|     34|     Yes|
| 14|  여성|  15|사무직| 35100.0|   16800|     98|    137|     Yes|
| 15|  남성|  12|사무직| 27300.0|   13500|     97|     66|      No|
| 16|  남성|  12|사무직| 40800.0|   15000|     97|     24|      No|
| 17|  남성|  15|사무직| 46000.0|   14250|     97|     48|      No|
| 18|  남성|  16|경영자|103750.0|   27510|     97|     70|      No|
| 19|  남성|  12|사무직| 42300.0|   14250|     97|    103|      No|
+---+------+----+------+--------+--------+-------+-------+--------+
only showing top 20 rows

In [ ]:
스파크DF.na.fill('NA').show()
# 스파크DF.fillna('NA').show()

+----+------+----+------+-------+--------+-------+-------+--------+
|  id|gender|educ|jobcat| salary|salbegin|jobtime|prevexp|minority|
+----+------+----+------+-------+--------+-------+-------+--------+
|null|  남성|  12|    NA|   null|    null|   null|   null|      NA|
|   0|    NA|null|사무직|60000.0|    null|     95|   null|     YES|
|null|    NA|null|    NA|   null|    null|   null|   null|      NA|
|   1|  남성|  15|경영자|57000.0|   27000|     98|    144|      No|
|   2|  남성|  16|사무직|40200.0|   18750|     98|     36|      No|
|   3|  여성|  12|사무직|21450.0|   12000|     98|    381|      No|
|   4|  여성|   8|사무직|21900.0|   13200|     98|    190|      No|
|   5|  남성|  15|사무직|45000.0|   21000|     98|    138|      No|
|   6|  남성|  15|사무직|32100.0|   13500|     98|     67|      No|
|   7|  남성|  15|사무직|36000.0|   18750|     98|    114|      No|
|   8|  여성|  12|사무직|21900.0|    9750|     98|      0|      No|
|   9|  여성|  15|사무직|27900.0|   12750|     98|    115|      No|
|  10|  여성|  12|사무직|24000.0|   13500|     98|    244|      No|
|  11|  여성|  16|사무직|30300.0|   16500|     98|    143|      No|
|  12|  남성|   8|사무직|28350.0|   12000|     98|     26|     Yes|
|  13|  남성|  15|사무직|27750.0|   14250|     98|     34|     Yes|
|  14|  여성|  15|사무직|35100.0|   16800|     98|    137|     Yes|
|  15|  남성|  12|사무직|27300.0|   13500|     97|     66|      No|
|  16|  남성|  12|사무직|40800.0|   15000|     97|     24|      No|
|  17|  남성|  15|사무직|46000.0|   14250|     97|     48|      No|
+----+------+----+------+-------+--------+-------+-------+--------+
only showing top 20 rows

In [ ]:
# 스파크DF.na.fill('NA','jobtime').show()
스파크DF.fillna('NA','jobtime').show()

+----+------+----+------+-------+--------+-------+-------+--------+
|  id|gender|educ|jobcat| salary|salbegin|jobtime|prevexp|minority|
+----+------+----+------+-------+--------+-------+-------+--------+
|null|  남성|  12|  null|   null|    null|   null|   null|    null|
|   0|  null|null|사무직|60000.0|    null|     95|   null|     YES|
|null|  null|null|  null|   null|    null|   null|   null|    null|
|   1|  남성|  15|경영자|57000.0|   27000|     98|    144|      No|
|   2|  남성|  16|사무직|40200.0|   18750|     98|     36|      No|
|   3|  여성|  12|사무직|21450.0|   12000|     98|    381|      No|
|   4|  여성|   8|사무직|21900.0|   13200|     98|    190|      No|
|   5|  남성|  15|사무직|45000.0|   21000|     98|    138|      No|
|   6|  남성|  15|사무직|32100.0|   13500|     98|     67|      No|
|   7|  남성|  15|사무직|36000.0|   18750|     98|    114|      No|
|   8|  여성|  12|사무직|21900.0|    9750|     98|      0|      No|
|   9|  여성|  15|사무직|27900.0|   12750|     98|    115|      No|
|  10|  여성|  12|사무직|24000.0|   13500|     98|    244|      No|
|  11|  여성|  16|사무직|30300.0|   16500|     98|    143|      No|
|  12|  남성|   8|사무직|28350.0|   12000|     98|     26|     Yes|
|  13|  남성|  15|사무직|27750.0|   14250|     98|     34|     Yes|
|  14|  여성|  15|사무직|35100.0|   16800|     98|    137|     Yes|
|  15|  남성|  12|사무직|27300.0|   13500|     97|     66|      No|
|  16|  남성|  12|사무직|40800.0|   15000|     97|     24|      No|
|  17|  남성|  15|사무직|46000.0|   14250|     97|     48|      No|
+----+------+----+------+-------+--------+-------+-------+--------+
only showing top 20 rows

In [ ]:
# 스파크DF.na.fill('NA',['gender','jobtime']).show()
스파크DF.fillna('NA',['gender','jobtime']).show()

+----+------+----+------+-------+--------+-------+-------+--------+
|  id|gender|educ|jobcat| salary|salbegin|jobtime|prevexp|minority|
+----+------+----+------+-------+--------+-------+-------+--------+
|null|  남성|  12|  null|   null|    null|   null|   null|    null|
|   0|    NA|null|사무직|60000.0|    null|     95|   null|     YES|
|null|    NA|null|  null|   null|    null|   null|   null|    null|
|   1|  남성|  15|경영자|57000.0|   27000|     98|    144|      No|
|   2|  남성|  16|사무직|40200.0|   18750|     98|     36|      No|
|   3|  여성|  12|사무직|21450.0|   12000|     98|    381|      No|
|   4|  여성|   8|사무직|21900.0|   13200|     98|    190|      No|
|   5|  남성|  15|사무직|45000.0|   21000|     98|    138|      No|
|   6|  남성|  15|사무직|32100.0|   13500|     98|     67|      No|
|   7|  남성|  15|사무직|36000.0|   18750|     98|    114|      No|
|   8|  여성|  12|사무직|21900.0|    9750|     98|      0|      No|
|   9|  여성|  15|사무직|27900.0|   12750|     98|    115|      No|
|  10|  여성|  12|사무직|24000.0|   13500|     98|    244|      No|
|  11|  여성|  16|사무직|30300.0|   16500|     98|    143|      No|
|  12|  남성|   8|사무직|28350.0|   12000|     98|     26|     Yes|
|  13|  남성|  15|사무직|27750.0|   14250|     98|     34|     Yes|
|  14|  여성|  15|사무직|35100.0|   16800|     98|    137|     Yes|
|  15|  남성|  12|사무직|27300.0|   13500|     97|     66|      No|
|  16|  남성|  12|사무직|40800.0|   15000|     97|     24|      No|
|  17|  남성|  15|사무직|46000.0|   14250|     97|     48|      No|
+----+------+----+------+-------+--------+-------+-------+--------+
only showing top 20 rows

결측값을 통계값으로 대체

In [ ]:
from pyspark.ml.feature import Imputer

In [ ]:
대체 = Imputer(
    inputCols=['educ','salary'],
    outputCols=["{}_imputed".format(c) for c in ['educ','salary']]
).setStrategy('mean')

In [ ]:
대체.fit(스파크DF).transform(스파크DF).show()

+----+------+----+------+-------+--------+-------+-------+--------+------------+-----------------+
|  id|gender|educ|jobcat| salary|salbegin|jobtime|prevexp|minority|educ_imputed|   salary_imputed|
+----+------+----+------+-------+--------+-------+-------+--------+------------+-----------------+
|null|  남성|  12|  null|   null|    null|   null|   null|    null|          12|34473.42105263158|
|   0|  null|null|사무직|60000.0|    null|     95|   null|     YES|          13|          60000.0|
|null|  null|null|  null|   null|    null|   null|   null|    null|          13|34473.42105263158|
|   1|  남성|  15|경영자|57000.0|   27000|     98|    144|      No|          15|          57000.0|
|   2|  남성|  16|사무직|40200.0|   18750|     98|     36|      No|          16|          40200.0|
|   3|  여성|  12|사무직|21450.0|   12000|     98|    381|      No|          12|          21450.0|
|   4|  여성|   8|사무직|21900.0|   13200|     98|    190|      No|           8|          21900.0|
|   5|  남성|  15|사무직|45000.0|   21000|     98|    138|      No|          15|          45000.0|
|   6|  남성|  15|사무직|32100.0|   13500|     98|     67|      No|          15|          32100.0|
|   7|  남성|  15|사무직|36000.0|   18750|     98|    114|      No|          15|          36000.0|
|   8|  여성|  12|사무직|21900.0|    9750|     98|      0|      No|          12|          21900.0|
|   9|  여성|  15|사무직|27900.0|   12750|     98|    115|      No|          15|          27900.0|
|  10|  여성|  12|사무직|24000.0|   13500|     98|    244|      No|          12|          24000.0|
|  11|  여성|  16|사무직|30300.0|   16500|     98|    143|      No|          16|          30300.0|
|  12|  남성|   8|사무직|28350.0|   12000|     98|     26|     Yes|           8|          28350.0|
|  13|  남성|  15|사무직|27750.0|   14250|     98|     34|     Yes|          15|          27750.0|
|  14|  여성|  15|사무직|35100.0|   16800|     98|    137|     Yes|          15|          35100.0|
|  15|  남성|  12|사무직|27300.0|   13500|     97|     66|      No|          12|          27300.0|
|  16|  남성|  12|사무직|40800.0|   15000|     97|     24|      No|          12|          40800.0|
|  17|  남성|  15|사무직|46000.0|   14250|     97|     48|      No|          15|          46000.0|
+----+------+----+------+-------+--------+-------+-------+--------+------------+-----------------+
only showing top 20 rows

In [ ]:
대체 = Imputer(
    inputCols=['educ','salary'],
    outputCols=["{}_imputed".format(c) for c in ['educ','salary']]
).setStrategy('mode')

대체.fit(스파크DF).transform(스파크DF).show()

+----+------+----+------+-------+--------+-------+-------+--------+------------+--------------+
|  id|gender|educ|jobcat| salary|salbegin|jobtime|prevexp|minority|educ_imputed|salary_imputed|
+----+------+----+------+-------+--------+-------+-------+--------+------------+--------------+
|null|  남성|  12|  null|   null|    null|   null|   null|    null|          12|       30750.0|
|   0|  null|null|사무직|60000.0|    null|     95|   null|     YES|          12|       60000.0|
|null|  null|null|  null|   null|    null|   null|   null|    null|          12|       30750.0|
|   1|  남성|  15|경영자|57000.0|   27000|     98|    144|      No|          15|       57000.0|
|   2|  남성|  16|사무직|40200.0|   18750|     98|     36|      No|          16|       40200.0|
|   3|  여성|  12|사무직|21450.0|   12000|     98|    381|      No|          12|       21450.0|
|   4|  여성|   8|사무직|21900.0|   13200|     98|    190|      No|           8|       21900.0|
|   5|  남성|  15|사무직|45000.0|   21000|     98|    138|      No|          15|       45000.0|
|   6|  남성|  15|사무직|32100.0|   13500|     98|     67|      No|          15|       32100.0|
|   7|  남성|  15|사무직|36000.0|   18750|     98|    114|      No|          15|       36000.0|
|   8|  여성|  12|사무직|21900.0|    9750|     98|      0|      No|          12|       21900.0|
|   9|  여성|  15|사무직|27900.0|   12750|     98|    115|      No|          15|       27900.0|
|  10|  여성|  12|사무직|24000.0|   13500|     98|    244|      No|          12|       24000.0|
|  11|  여성|  16|사무직|30300.0|   16500|     98|    143|      No|          16|       30300.0|
|  12|  남성|   8|사무직|28350.0|   12000|     98|     26|     Yes|           8|       28350.0|
|  13|  남성|  15|사무직|27750.0|   14250|     98|     34|     Yes|          15|       27750.0|
|  14|  여성|  15|사무직|35100.0|   16800|     98|    137|     Yes|          15|       35100.0|
|  15|  남성|  12|사무직|27300.0|   13500|     97|     66|      No|          12|       27300.0|
|  16|  남성|  12|사무직|40800.0|   15000|     97|     24|      No|          12|       40800.0|
|  17|  남성|  15|사무직|46000.0|   14250|     97|     48|      No|          15|       46000.0|
+----+------+----+------+-------+--------+-------+-------+--------+------------+--------------+
only showing top 20 rows

In [ ]:
스파크DF.dtypes

[('id', 'int'),
 ('gender', 'string'),
 ('educ', 'int'),
 ('jobcat', 'string'),
 ('salary', 'double'),
 ('salbegin', 'int'),
 ('jobtime', 'int'),
 ('prevexp', 'int'),
 ('minority', 'string')]

In [ ]:
from pyspark.sql.types import StringType

In [ ]:
수치변수=[변수.name for 변수 in 스파크DF.schema.fields if not isinstance(변수.dataType, StringType)]
수치변수

['id', 'educ', 'salary', 'salbegin', 'jobtime', 'prevexp']

In [ ]:
스파크DF[수치변수].show()

+----+----+-------+--------+-------+-------+
|  id|educ| salary|salbegin|jobtime|prevexp|
+----+----+-------+--------+-------+-------+
|null|  12|   null|    null|   null|   null|
|   0|null|60000.0|    null|     95|   null|
|null|null|   null|    null|   null|   null|
|   1|  15|57000.0|   27000|     98|    144|
|   2|  16|40200.0|   18750|     98|     36|
|   3|  12|21450.0|   12000|     98|    381|
|   4|   8|21900.0|   13200|     98|    190|
|   5|  15|45000.0|   21000|     98|    138|
|   6|  15|32100.0|   13500|     98|     67|
|   7|  15|36000.0|   18750|     98|    114|
|   8|  12|21900.0|    9750|     98|      0|
|   9|  15|27900.0|   12750|     98|    115|
|  10|  12|24000.0|   13500|     98|    244|
|  11|  16|30300.0|   16500|     98|    143|
|  12|   8|28350.0|   12000|     98|     26|
|  13|  15|27750.0|   14250|     98|     34|
|  14|  15|35100.0|   16800|     98|    137|
|  15|  12|27300.0|   13500|     97|     66|
|  16|  12|40800.0|   15000|     97|     24|
|  17|  15|46000.0|   14250|     97|     48|
+----+----+-------+--------+-------+-------+
only showing top 20 rows

In [ ]:
대체 = Imputer(
    inputCols=수치변수,
    # outputCols=["{}_imputed".format(c) for c in 수치변수]
    outputCols=수치변수
).setStrategy('mean')

대체.fit(스파크DF).transform(스파크DF).show()

+---+------+----+------+-----------------+--------+-------+-------+--------+
| id|gender|educ|jobcat|           salary|salbegin|jobtime|prevexp|minority|
+---+------+----+------+-----------------+--------+-------+-------+--------+
|237|  남성|  12|  null|34473.42105263158|   17016|     81|     95|    null|
|  0|  null|  13|사무직|          60000.0|   17016|     95|     95|     YES|
|237|  null|  13|  null|34473.42105263158|   17016|     81|     95|    null|
|  1|  남성|  15|경영자|          57000.0|   27000|     98|    144|      No|
|  2|  남성|  16|사무직|          40200.0|   18750|     98|     36|      No|
|  3|  여성|  12|사무직|          21450.0|   12000|     98|    381|      No|
|  4|  여성|   8|사무직|          21900.0|   13200|     98|    190|      No|
|  5|  남성|  15|사무직|          45000.0|   21000|     98|    138|      No|
|  6|  남성|  15|사무직|          32100.0|   13500|     98|     67|      No|
|  7|  남성|  15|사무직|          36000.0|   18750|     98|    114|      No|
|  8|  여성|  12|사무직|          21900.0|    9750|     98|      0|      No|
|  9|  여성|  15|사무직|          27900.0|   12750|     98|    115|      No|
| 10|  여성|  12|사무직|          24000.0|   13500|     98|    244|      No|
| 11|  여성|  16|사무직|          30300.0|   16500|     98|    143|      No|
| 12|  남성|   8|사무직|          28350.0|   12000|     98|     26|     Yes|
| 13|  남성|  15|사무직|          27750.0|   14250|     98|     34|     Yes|
| 14|  여성|  15|사무직|          35100.0|   16800|     98|    137|     Yes|
| 15|  남성|  12|사무직|          27300.0|   13500|     97|     66|      No|
| 16|  남성|  12|사무직|          40800.0|   15000|     97|     24|      No|
| 17|  남성|  15|사무직|          46000.0|   14250|     97|     48|      No|
+---+------+----+------+-----------------+--------+-------+-------+--------+
only showing top 20 rows